### PR TITLE
RTL Support 

### PR DESCRIPTION
**Pull request by iMajeed16**
* `textDirection` added for rtl languages.
* `textDirection` by default would be `TextDirection.ltr`.

### CODE REVIEW

**Comment by Yahllil** [comment]
Doesn't work. Seems to be displaying the text on the left even when setting `TextDirection.ltr`

**Comment by iMajeed16** [comment]
> Doesn't work. Seems to be displaying the text on the left even when setting `TextDirection.ltr`

Did you mean `TextDirection.rtl`?. ltr it would be for the text from left to right and thus it will be on the left side.

Check this [example ](https://github.com/cmdrootaccess/another-flushbar#rtl-text).

**Comment by Yahllil** [comment]
> > Doesn't work. Seems to be displaying the text on the left even when setting `TextDirection.ltr`
> 
> Did you mean `TextDirection.rtl`?. ltr it would be for the text from left to right and thus it will be on the left side.
> 
> Check this [example ](https://github.com/cmdrootaccess/another-flushbar#rtl-text).

Yes sorry, I've edited my comment. It does not work when setting `TextDirection.rtl`. The Text still appears on the left side

**Comment by iMajeed16** [comment]
> > > Doesn't work. Seems to be displaying the text on the left even when setting `TextDirection.ltr`
> > 
> > 
> > Did you mean `TextDirection.rtl`?. ltr it would be for the text from left to right and thus it will be on the left side.
> > Check this [example ](https://github.com/cmdrootaccess/another-flushbar#rtl-text).
> 
> Yes sorry, I've edited my comment. It does not work when setting `TextDirection.rtl`. The Text still appears on the left s

> > > Doesn't work. Seems to be displaying the text on the left even when setting `TextDirection.ltr`
> > 
> > 
> > Did you mean `TextDirection.rtl`?. ltr it would be for the text from left to right and thus it will be on the left side.
> > Check this [example ](https://github.com/cmdrootaccess/another-flushbar#rtl-text).
> 
> Yes sorry, I've edited my comment. It does not work when setting `TextDirection.rtl`. The Text still appears on the left side

Could you please provide me some code?

**Comment by Yahllil** [comment]
> > Yes sorry, I've edited my comment. It does not work when setting `TextDirection.rtl`. The Text still appears on the left side
> 
> Could you please provide me some code?

Of course:

```
Flushbar(
      title: 'My title',
      message: 'My message',
      backgroundColor: Colors.red,
      titleColor: Colors.white,
      messageColor: Colors.white,
      borderRadius: BorderRadius.circular(25),
      flushbarPosition: FlushbarPosition.TOP,
      textDirection: TextDirection.rtl,
      onTap: (_) {
        print('Tapped');
      },
      animationDuration: const Duration(milliseconds: 500),
      duration: const Duration(seconds: 3),
    )..show(context);
```

**Comment by iMajeed16** [comment]
> Of course:
> 
> ```
> Flushbar(
>       title: 'My title',
>       message: 'My message',
>       backgroundColor: Colors.red,
>       titleColor: Colors.white,
>       messageColor: Colors.white,
>       borderRadius: BorderRadius.circular(25),
>       flushbarPosition: FlushbarPosition.TOP,
>       textDirection: TextDirection.rtl,
>       onTap: (_) {
>         print('Tapped');
>       },
>       animationDuration: const Duration(milliseconds: 500),
>       duration: const Duration(seconds: 3),
>     )..show(context);
> ```

After some testing if the app language is in a language that is left to right it would show it in that way even if you added `TextDirection.rtl`. and it depends of that. 

To be clear this is only effect the indicator (the left bar) to be showed on the right if you set it to `TextDirection.rtl`.

**Comment by Yahllil** [comment]
> > Of course:
> > ```
> > Flushbar(
> >       title: 'My title',
> >       message: 'My message',
> >       backgroundColor: Colors.red,
> >       titleColor: Colors.white,
> >       messageColor: Colors.white,
> >       borderRadius: BorderRadius.circular(25),
> >       flushbarPosition: FlushbarPosition.TOP,
> >       textDirection: TextDirection.rtl,
> >       onTap: (_) {
> >         print('Tapped');
> >       },
> >       animationDuration: const Duration(milliseconds: 500),
> >       duration: const Duration(seconds: 3),
> >     )..show(context);
> > ```
> 
> After some testing if the app language is in a language that is left to right it would show it in that way even if you added `TextDirection.rtl`. and it depends of that.
> 
> To be clear this is only effect the indicator (the left bar) to be showed on the right if you set it to `TextDirection.rtl`.

So what is the solution for presenting the alert's text as RTL?

**Pull request merged**
